### ISSUE TITLE
informações do banco de dados como variavel de sistema

### ISSUE THREAD

**Issue by rafaelbantu** [Quijaua/floema#16]

**Comment by CauaSerpa** [comment]
### Resolução da Issue: Informações do banco de dados como variável de sistema

**Detalhes da Resolução:**
Nesta atualização, tomamos medidas para reforçar a segurança do sistema, removendo todas as informações confidenciais de conexão com o banco de dados dos arquivos **"config.php"** e **"back-end/config.php"**. Essas informações sensíveis foram transferidas para um arquivo **".env"**, onde são gerenciadas como variáveis de ambiente, proporcionando um nível adicional de segurança.

**Arquivos Afetados:**
> .env_sample
> config.php
> back-end/config.php

**Quando os arquivos foram afetados:**
1. Commit 7f749c9
> .env_sample
> .config.php

2. Commit 28b443a
> back-end/config.php

Com esta implementação, encerramos com sucesso a issue #16.
